version: "3"
services:
 web:
  # replace username/repo:tag with your name and image details
  image: harryyhzhang/quickstart-python
  deploy:
   replicas: 5
   resources:
    limits:
     cpus: "0.1"
     memory: 50M
   restart_policy:
    condition: on-failure
  ports:
   - "8888:80"
  networks:
   - webnet
 proxy:
   image: haproxy
   command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg
   ports: 
    - "80:80"
   volumes: 
    - "/home/docker/haproxy:/usr/local/etc/haproxy"
   deploy:
    placement:
      constraints: [node.role == manager]
   networks:
    - webnet
 visualizer:
  image: dockersamples/visualizer:stable
  ports:
   - "8080:8080"
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  deploy:
   placement:
    constraints: [node.role == manager]
  networks:
   - webnet
 redis:
  image: redis
  ports:
   - "6379:6379"
  volumes:
   - /home/docker/data:/data
  deploy:
   placement:
    constraints: [node.role == manager]
  command: redis-server --appendonly yes
  networks:
   - webnet
networks:
 webnet: